# Generated by Django 5.0.1 on 2024-12-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_user_repassword_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
